import json,re
from pathlib import Path
p=Path('toc-final.json');d=json.loads(p.read_text());toc=Path('src/lib/grammar/toc.ts');ts=toc.read_text()
changes={
133: ('Hine, Akusu, and Narrative Progression', 'Successive information, related developments, regional and genre preferences, participant changes, and attributed narrative-boundary analyses.'),
134: ('Kor: Simultaneity, Habits, and Conditions', 'Overlapping situations with shared or different subjects, continuative constructions, habitual and factual uses, regional forms, and historical proposals.'),
135: ('Conditional, Temporal, and Concessive Constructions', 'Premises with yakun, evaluation with yak, regional ciki and cik uses, factual sequences, wishes, and hypothetical or realized concessions.'),
136: ('Reasons, Purposes, and Desired Outcomes', 'Kusu, wa kusu, hi kusu, kunine, participant relations, independent connective uses, and regional functions.'),
137: ('Manner, Appearance, Degree, and Comparison', 'No and its word-class boundary, koraci, source-specific appearance analyses, extent clauses, and degree-adjunct relativization.'),
138: ('Narrative Continuation and Repetition', 'Connective formal nouns, orowa expressions, recapitulation and reference, and attributed analyses of narrative boundaries.'),
127: ('Absence and Lack: Isam and Sak', 'Negative existential and possessive predicates, subject and object contrasts, lexical alternatives, figurative completion, and an attributed historical proposal.'),
128: ('Inability, Inexperience, and Lack of Knowledge', 'Lexical contrasts, independent and auxiliary uses, capacity and circumstances, and dialect and register restrictions.'),
129: ('Indefinite Expressions and Negation', 'Affirmative and negative readings, interrogative and indefinite bases, variable ka meanings, free choice, and the placement of negation.'),
130: ('Prohibitions with Iteki and Related Forms', 'Bare imperative and person-marked directives, regional prohibitives, placement, plural and polite address, and advisory expressions.'),
131: ('Clause Linkage and Its Analyses', 'Unchanged verb forms, connective categories, competing structural accounts, participant reference, and the principal linking relations.'),
132: ('Wa, Connected Events, and Ayne', 'Sequence, causation, manner and result states, shared and different subjects, duration with ayne, and source-specific negative and phonological patterns.'),
30: ('Citation Forms and Morphophonological Alternations', 'Final-consonant pronunciation, prefix contraction, possessive morphology, and lexical history, with separate conditions for each pattern.'),
31: ('Person Markers: Contraction, Accent, and Suffix Boundaries', 'Dialect-specific person-prefix contraction, initial-vowel weakening, accent behavior, and pronunciation at person-suffix boundaries.'),
32: ('Reduplication and Phonological Alternations', 'Root, partial, and whole-stem reduplication, their lexical restrictions, and documented consonant and boundary effects.'),
33: ('Word Classes and Their Diagnostics', 'The major classification schemes and their grammatical diagnostics, including person marking, dependence, modification, and disputed category boundaries.'),
34: ('Nominal Subclasses and Dependence', 'Common nouns, locative nouns, pronouns, and formal nouns, compared through possession, independence, modification, and grammatical location.'),
35: ('Formal Nouns and Nominalizing Constructions', 'Dependent nominal heads, their modifiers, and the competing analyses of relative, complement, and evidential uses.'),
36: ('Verb Classes, Arguments, and Person Marking', 'Verb subclasses defined through person marking and argument structure, including zero-argument predicates, locative objects, copular complements, and derived higher-valency forms.'),
37: ('Property Predicates and the Adjective Analysis', 'The verbal morphology and syntax of property predicates, their state and change readings, and the modern and historical classification debates.'),
38: ('Diminutive and Affective Noun Formation', 'The suffix -po, lexicalized formations, regional okkaypo meanings, and historical Horobetsu kinship uses.'),
39: ('Nominal Compounds and Their Structure', 'Compound diagnostics, six documented formation patterns, nominal conversion, and lexicalization at the phrase boundary.'),
40: ('Noun Formation from Verbs and Nouns', 'Nominalizing forms, lexical person-shaped prefixes, conversion, and the relationship between lexical nouns and clause-level constructions.'),
41: ('Nominal Number and Utar', 'Number-neutral nouns, plural and associative utar, lexical plurals, and source differences over animacy and possession.'),
42: ('Noun-Phrase Structure', 'Modifiers, demonstratives, numerals, locative expressions, possession, and coordination, with attributed differences in analysis.'),
43: ('Possessive Constructions and Alienability', 'Possession with kor and affiliative nouns, lexical and dialect variation, and the limits of semantic classifications.'),
44: ('Concept, Affiliative, and Personal Forms', 'Possessive noun forms, short and long variants, person marking, and the interpretation of expressed and unspecified possessors.'),
45: ('Affiliative Suffix Patterns', 'Phonological conditions, lexical suffix classes, exceptional forms, and attributed historical analyses of possessive morphology.'),
46: ('Adnominal Possession and Double Marking', 'Possessor phrases, head marking, kor with affiliative nouns, classifier verbs, and nested possessive relations.'),
47: ('Possessors in Noun Incorporation', 'Possessor-to-subject incorporation, its person marking, and the different restrictions on object incorporation.'),
48: ('Kinship, Address, and Possession', 'Lexical and dialect differences in kinship possession, reference and address, honorific fourth person, and narrative possession.'),
49: ('Independent Personal Pronouns', 'Dialect-specific pronoun paradigms, emphasis and contrast, third-person expressions, and the boundary between pronouns and possessed group nouns.'),
50: ('Demonstratives and Reference', 'Saru demonstrative modifiers, spatial and discourse reference, formal-noun combinations, and regional differences.'),
51: ('Interrogative and Indefinite Expressions', 'Question-word classes, their dialect forms and sentence patterns, and their relationship to indefinite expressions.'),
52: ('Relational Nouns, Spatial Forms, and Quasi-Incorporation', 'Locative noun classes, person marking, basic and long forms, spatial meanings, and Satō’s quasi-incorporation analysis of or.'),
53: ('Place Particles and Motion Expressions', 'Location, direction, origin, area, and route constructions, their dialect differences, and their relationship to postposed adverbs and translative ne.'),
54: ('Numeral Forms and Counting Systems', 'Adnominal, nominal, and enumeration forms, vigesimal composition, overcounting, and regional decimal systems.'),
55: ('Numeral Syntax, Ordinals, and Quantity', 'Numeral position and independent use, compound counts, classifier analyses, ordinal expressions, and the interaction of quantity with number.'),
56: ('The Verb Word and Its Boundaries', 'Source-specific derivational templates, argument structure, number morphology, person zones, and the distinction between a verb word and quasi-incorporation.'),
57: ('Transitivity and Valency Classes', 'Argument frames, ambient and experienced states, locative objects, copular person marking, higher valency, and competing analyses of arity.'),
58: ('Verbal Number and Stem Alternation', 'Lexical number pairs, participant and event number, dialect forms, additional pa and ci, and the effects of respect and narrative person.'),
59: ('Ki, Support Constructions, and Pro-Verbs', 'Lexical, formal, assertive, poetic, and referential uses of ki, with their person-marking patterns and dialect differences.'),
60: ('Verb Formation from Nouns and Verbal Roots', 'Lexicalized nominal formations, bound roots, transitivity pairs, different uses of kar, and intensive no.'),
61: ('Adverbial and Intensive No', 'Manner formation, lexical restrictions, unsuffixed adverbs, clause-linking no, and distinct intensive verbal forms.'),
62: ('Person Marking and Argument Roles', 'Basic S, A, and O paradigms, person-conditioned alignment, interaction forms, zero third person, and the morphological status of person markers.'),
63: ('First- and Second-Person Singular', 'Subject and object forms, regional contraction, neutral second-person alignment, and the interaction paradigm.'),
64: ('First-Person Plural and Clusivity', 'Exclusive and inclusive reference, subject and object forms, narrative uses, and dialect-specific analyses of group reference.'),
65: ('Eci and Person Interactions', 'Second-plural marking, the Saru/Chitose first-to-second portmanteau, reverse interactions, and regional and literary alternatives.'),
66: ('Object Indexing and Three-Place Verbs', 'The object series, recipient and theme indexing, third-person zero, and the distinction between person indexes and semantic arguments.'),
67: ('Fourth-Person Forms and Their Uses', 'Inclusive, indefinite, honorific, narrative, and quoted-speaker reference, with dialect differences in form and number and competing semantic analyses.'),
68: ('Fourth Person in Respectful Address', 'Honorific person forms, verbal number, speaker and family differences, regional alternatives, and the distinction from narrative and quoted-speaker uses.'),
69: ('Person-Marker Order and Stem Boundaries', 'Prefix sequences, portmanteaux, prefix–suffix combinations, additional number marking, and evidence for separable person forms.'),
70: ('Person and Verbal Number', 'Participant number, comitative grouping, numeral constructions, fourth-person mismatches, and additional plural morphology.'),
71: ('Intransitive Subjects and Semantic Roles', 'Subject marking of agents, patients, and experiencers, lexical classes in incorporation, and the difference between valency and person-conditioned alignment.'),
72: ('Mixed Alignment and Hierarchical Analyses', 'The Hokkaido person-conditioned patterns, interaction forms, the Sakhalin inverse proposal, and the separate questions raised by lexical classes and voice.'),
73: ('Valency and Voice Constructions', 'Argument structure, person-index diagnostics, principal derivational effects, lexical formation, and competing voice analyses.'),
74: ('The Productive Causative -re, -te, and -e', 'Suffix forms, causee marking, direct and indirect causation, permissive and coercive readings, lexical restrictions, and a Horobetsu clause-linkage proposal.'),
75: ('Lexical Verb Pairs and Causative -ka', 'Root-based forming suffixes, motion causatives, regional -ka variation, derived bases, and competing classifications of causative morphology.'),
76: ('Causees and Multiple Causative Layers', 'Causee objects, retained themes, different analyses of double causation, four-participant textual evidence, and restrictions on causee backgrounding.'),
77: ('Indefinite Causative -yar and -ar', 'Valency-retaining causation, retained objects, oblique causees, conflicting suffix distributions, and older plural and Ishikari analyses.'),
78: ('Applicative Constructions and Their Arguments', 'The three applicative prefixes, changes in argument structure and person marking, overlapping semantic roles, and source-specific classifications.'),
79: ('The e- Applicative', 'Instrument, purpose, content, and place relations, with Nakagawa’s four constructional subtypes and Bugaeva’s lexical classification.'),
80: ('The ko- Applicative', 'Directed and comitative relations, spatial and personal goals, source objects, instrumental uses, and incorporation.'),
81: ('The o- Applicative', 'Applied places, motion goals, contrasts with ko-, and differing source descriptions of source and instrumental meanings.'),
82: ('Multiple Applicatives, Incorporation, and Relative Clauses', 'Documented applicative combinations, noun incorporation and prefix order, and relative clauses with applied objects or retained role markers.'),
83: ('Antipassive and Unspecified-Object i-', 'Object backgrounding, person marking, conventional activities, interaction with applicatives, lexical exceptions, and competing historical accounts.'),
84: ('Reflexive yay- and Its Extensions', 'Participant identity, intentionality and direct-reflexive analyses, reflexive possession, lexical extensions, and combinations with si-.'),
85: ('Reflexive si- in Verbal and Spatial Constructions', 'Bodily motion and change, indirect reflexivity, causatives and pretending, locative coreference, and proposed historical developments.'),
86: ('Reciprocal u- and Joint Participation', 'Canonical and indirect reciprocals, object-oriented constructions, incorporated possessors, and the distinction between reciprocal and sociative forms.'),
87: ('Middle ci- and the Passive Analysis', 'Middle and resultative descriptions, person restrictions, agent phrases, competing analyses of passive patients, and anticausative meanings.'),
88: ('Object Noun Incorporation', 'Wordhood and person diagnostics, remaining objects, generic reference, incorporated compound nouns, two-object formations, and possession restrictions.'),
89: ('Subject Incorporation and External Possessors', 'Natural-phenomenon predicates, possessed stems with external subjects, natural-force actors, changes in grammatical relation, and competing restrictions.'),
90: ('Incorporation, Quasi-Incorporation, and Word Structure', 'Applicative-related incorporation, affix order, Tamura’s 連他動詞, Satō’s lexical quasi-incorporation, Nakagawa’s one-word and two-word forms, and the theoretical debates.'),
91: ('Manner Compounds and Adverbial Incorporation', 'Property-verb components, derived adverbs, lexicalized mono, temporal nouns, and source disagreements over productivity.'),
92: ('Constituent Order and the Verb-Final Clause', 'Preverbal noun phrases and adverbials, differing accounts of participant order, head-final phrases, clause endings, and later specifications with ki.'),
93: ('Argument Realization and Person Indexing', 'Argument count, person forms, omitted noun phrases, unindexed themes, incorporation, and locative role information.'),
94: ('Noun Phrases and Pronominal-Argument Analyses', 'Head marking, Satō’s layered clause analysis, unindexed core arguments, shared argumenthood, and the limits of word-order and quantifier evidence.'),
95: ('Oblique Expressions and Verbless Utterances', 'Locative objects and adjuncts, complete noun-phrase utterances, echo questions, formal-noun endings, and ambient predicate boundaries.'),
97: ('Existential and Locational Predicates', 'Existence, personal location, regional plural forms, narrative number, seasonal change, continuation, and lexical absence.'),
98: ('Predicative Possession', 'Possessor and possessee subjects, kor and existential constructions, kinship and affiliation, source-specific corpus findings, incorporation, and lack.'),
99: ('Property Predicates', 'Direct predication and person marking, state and change readings, manner and auxiliary uses, ambient conditions, and the adjective debate.'),
100: ('Copular Negation and Clause Endings', 'Negative nominal predicates, evidential endings, polar and content questions, scope, ordering restrictions, and competing structural analyses.'),
101: ('P and Pe: Participants, Content, and Clause Endings', 'Sound-conditioned forms, phrase scope, relative participants, instrumental heads, content nominalization, human reference, and normative and linking uses.'),
103: ('Relative Clauses and Accessible Relations', 'Prenominal heads, argument roles, retained oblique relations, locative and possessive morphology, source qualifications, and comparison equivalents.'),
104: ('General Heads, Gapless Clauses, and Internal-Head Analyses', 'Overt light heads, complement relations, and Dal Corso’s source-limited incorporation and internally headed relative proposals.'),
105: ('Quotation, Logophoric Speech, and Indirect Reports', 'Quoted person reference, the syntactic reassessment of logophoric speech, indirect content, ordering flexibility, and regional predicate selection.'),
106: ('Nominalized Complements and Complex Predicates', 'Complement functions, sensory content, overt and zero nominalization, bare verb and auxiliary constructions, and participant reference.'),
107: ('Kuni, Indirect Complements, and Purpose Clauses', 'Prospective and inferential content, kunak and yak, reported instructions with causatives, kunine purpose linkage, and nominal expressions.'),
108: ('Time, Aspect, Modality, and Evidentiality', 'Contextual time reference, construction types, competing a and aan analyses, existential combinations, participant identity, and dialect restrictions.'),
109: ('Time Reference Without Obligatory Tense', 'Contextual event time, speech-time and narrative reference points, prospective expressions, and the interpretation of unmarked predicates.'),
110: ('Existential Aspect: Kor An and Wa An', 'Activities, habits, resulting states, person and number controllers, lexical interpretation, negative constructions, and regional limits.'),
111: ('A, Rok, and Aan: Earlier Situations and Discovery', 'Contextual contrasts, participant number, sustained and repeated events, retrospective discovery, regional forms, and competing aspectual analyses.'),
112: ('Kane An, Regional Continuatives, and Appearance', 'Ongoing and resulting states, degree and emphasis, Shizunai and Samani patterns, Tokachi and Ishikari forms, and distinct evidential constructions.'),
113: ('Completion, Repetition, and Event Phases', 'Finishing and disappearance, person marking on supplementary verbs, nisa, brief actions, ranke, contextual beginnings, and persistent results.'),
114: ('Commands, Requests, and Prohibitions', 'Direct imperative morphology, plural and polite forms, requests and final particles, indirect directives, and regional prohibitive expressions.'),
115: ('Invitations, Deliberation, and Wishes', 'Inclusive and other-person ro constructions, regional endings, Shizunai na, self-directed so, and wishes with ta and oka.'),
116: ('Desire, Rusuy, and Compound Predicates', 'Separate auxiliaries and lexical compounds, person placement, the desirer and action participant, impending feelings, and competing incorporation analyses.'),
117: ('Ability and Inability', 'Easkay and eaykap, person-marked lexical uses, compounds, ka, dialect and register limits, and more specific obstacles to action.'),
118: ('Necessity, Advice, and Permission', 'Easirki, obligation and expectation with kuni, conditional advice and permission, and ordinary person marking in indirect directives.'),
119: ('Conjecture, Intention, and Prospective Events', 'Contextual nankor, kusu ne and regional kusu ki, impending events, competing oasi analyses, seeming, circumlocution, and conditional context.'),
120: ('Formal Nouns and Evidential Constructions', 'The four noun families, internal complements and clause endings, regional frames, competing semantic accounts, negation, and construction-specific ordering.'),
121: ('Ruwe: Fact, Knowledge, and Clause Endings', 'Personal circumstances and explanations, nominal morphology, questions and replies, knowledge-based analyses, negation, and lexical ruwe an.'),
122: ('Siri: Visible Appearance and Ongoing Situations', 'Appearance and identity, descriptions of the speaker’s conduct, visual inference, aspectual and lexical uses, and Tokachi predication restrictions.'),
123: ('Hawe: Voice, Wording, and Reports', 'The speaker’s own wording, immediate reports, questions about meaningful cries, nominal morphology, and hawe as in inference and reported discourse.'),
124: ('Humi: Sensation and Internal Experience', 'Bodily and emotional experience, humi ne continuations, sound-based questions, Tokachi and Shizunai evidence, and the absence of a sensation.'),
125: ('Evidential Combinations, Discovery, and Structural Change', 'Exclamation and aan, double evidentials, construction-specific ordering, competing constituency analyses, grammaticalization proposals, and regional endings.'),
126: ('Clausal Negation with Somo', 'Preverbal and postverbal negatives, ka and the somo ki analysis, nominal predicates, evidential scope, regional forms, and construction-specific limits.'),
102: ('Lexical Heads and Formal-Noun Nominalization', 'Hi and place/time relations, sensory complements, conventional words and relative phrases, Tokachi independent endings, and Horobetsu adverbial clauses.'),
96: ('Copular ne and Nominal Predication', 'Identity and classification, subject marking without object indexes, syntactic and semantic valency, state and change readings, negation, and attributive ne.')
}
for part in d['parts']:
 for c in part['chapters']:
  if c['num'] not in changes:continue
  c['title'],c['summary']=changes[c['num']]
  raw=(Path('src/lib/grammar/chapters')/(c['slug']+'.svelte')).read_text()
  c['sections']=re.findall(r'<S\s+t="([^"]+)"',raw)
  keys=set(re.findall(r'<Ref\s+k="([^"]+)"',raw))
  for cites in re.findall(r'\bcite="([^"]+)"',raw):
   for cite in cites.split(';'):keys.add(cite.strip().split(':')[0])
  c['sources']=sorted(keys);c.pop('novelNote',None)
  pattern=r'(slug: '+re.escape(json.dumps(c['slug']))+r',\s*title: )"[^"\n]*(?:\\"[^"\n]*)*"'+r'(,\s*summary: )"[^"\n]*(?:\\"[^"\n]*)*"'
  ts,count=re.subn(pattern,lambda m:m[1]+json.dumps(c['title'],ensure_ascii=False)+m[2]+json.dumps(c['summary'],ensure_ascii=False),ts)
  assert count==1,(c['slug'],count)
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');toc.write_text(ts)
